# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Graphir.API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SOLUTION: '**/*.sln'
  BUILDPLATFORM: 'Any CPU'
  BUILDCONFIGURATION: 'Release'
  AZURE_SUBSCRIPTION_ID: '893ec71e-95c9-422b-8a39-4f0db30e2467' # HLS Hack Internal
  AZURE_RESOURCE_GROUP: 'rg-graphir'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build API
      run: dotnet build ./Graphir.API --configuration Release

    - name: create API artifact
      run: dotnet publish ./Graphir.API -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload API artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  provision:
    name: Provision Azure Resources
    runs-on: ubuntu-latest    
    outputs:
      azure-webapp-name: ${{ steps.deploy-bicep.outputs.appServiceAppName }}
    steps:                
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy BICEP Template
      id: deploy-bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./deploy/templates/main.bicep  # Set this to the location of your template file

  deploy_webapp:
    name: Deploy HackAPI
    runs-on: ubuntu-latest
    needs: [build, provision]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download API artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
        path: ${{ github.workspace }}/webapp    

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.provision.outputs.azure-webapp-name }}
        package: ./webapp

    - name: logout
      run: |
        az logout
